apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-permission2
  description: demo demo demo demo
  annotations:
    jira/project-key: SPP
    github.com/project-slug: github.com?owner=backstage-dummy-org&repo=test-permission2
  tags:
    - testing
  links:
    - url: https://www.google.co.uk/
      title: Main project documentation
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: group:default/spp-sml
