apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-permission2
  annotations:
    github.com/project-slug: github.com?owner=backstage-dummy-org&repo=test-permission2
  tags: |2-
    
     - python,
     -  java,
     -  typescript+
     - spp-sml,
     -  sml,
     -  ons
  links:
    - title: Supporting Documentation
      icon: dashboard
    - title: Build Documentation
      icon: dashboard
    - title: Deploy Documentation
      icon: dashboard
    - title: Release
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: group:default/spp-sml
