apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-permission2
  description: demo
  annotations:
    jira/project-key: SPP
    github.com/project-slug: github.com?owner=backstage-dummy-org&repo=test-permission2
  tags:
    - null
  links:
    - url: https://confluence.ons.gov.uk/display/SEC/SDP%3A+Core+features
      title: "Confluence "
      icon: dashboard
spec:
  type: website
  lifecycle: testing
  owner: group:default/spp-sml
