apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-permission2
  description: example
  annotations:
    jira/project-key: SPP
    github.com/project-slug: github.com?owner=backstage-dummy-org&repo=test-permission2
  tags:
    - demo
  links:
    - url: https://confluence.ons.gov.uk/display/SEC/SDP+Homepage
      title: Main project documentation
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: group:default/spp-sml
